kind: Deployment
apiVersion: apps/v1
metadata:
  name: factorio-dep
spec:
  selector:
    matchLabels:
      app: factorio-dep
  template:
    metadata:
      labels:
        app: factorio-dep
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: factorio
          image: factoriotools/factorio:1.1.68
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
          securityContext:
            runAsUser: 845
            runAsGroup: 845
          ports:
            - name: factorio-rcon
              containerPort: 27015
              protocol: TCP
            - name: factorio-udp
              containerPort: 34197
              protocol: UDP
          volumeMounts:
            - name: factorio-data
              mountPath: /factorio
            - name: factorio-config
              mountPath: /factorio/config/server-settings.json
              subPath: server-settings.json
              readOnly: false
            - name: factorio-whitelist
              mountPath: /factorio/config/server-whitelist.json
              subPath: server-whitelist.json
              readOnly: false
      volumes:
        - name: factorio-data
          persistentVolumeClaim:
            claimName: factorio-data
        - name: factorio-config
          configMap:
            name: factorio-settings
        - name: factorio-whitelist
          configMap:
            name: factorio-whitelist
